sudo: required
services: 
  - docker

before_install: 
  - docker build -t dmgolovin/docker-react -f Dockerfile.dev .

script:
  - docker run dmgolovin/docker-react npm run test  -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-265762056039"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
